name: 'Gobra'
description: 'Verify your Go project with Gobra'
inputs:
  caching:
    description: 'Enable caching of verification results. The possible values are 0 (disabled) and 1 (enabled).'
    required: true
    default: '1' # cache enabled by default
  projectLocation:
    description: 'Location in which the project is located in the workflow context. By default, it looks in a folder with the same name as the repository.'
    required: false
  includePaths:
    description: 'Directories used for package lookup. Their paths are relative to the project location.'
    required: false
  files:
    description: 'List of Go and Gobra files to verify.'
    required: false
  packages:
    description: 'Names of the packages to verify. By default, all packages are verified.'
    required: false
  excludePackages:
    description: 'Names of packages that should not be verified. This option takes precedence over the `package` option.' 
    required: false
  recursive:
    description: 'Verify nested packages recursively'
    required: false
    default:  '0'
  chop:
    description: 'Maximum number of files in which a file can be split with the chopper feature of Gobra. Larger values may improve the verification time of large codebases.'
    default: '1'
  viperBackend:
    description: 'Which Viper backend to use. Can be one of "SILICON", "VSWITHSILICON", "CARBON", and "VSWITHCARBON".'
    required: true
    default: "VSWITHSILICON" # to allow caching by default
  javaXss:
    description: 'Java stack size. Should be increased in case of frequent stack overflows.'
    required: true
    default: '128m'
  javaXmx:
    description: 'Maximum size of the heap.'
    required: true
    default: '4g'
  globalTimeout:
    description: 'Time-out for the entire Gobra Action. Note that a GitHub workflow step times-out automatically after 6 hours.'
    required: true
    default: '6h'
  packageTimeout:
    description: 'Time-out for the verification of a single package.'
    required: false
  imageName:
    description: 'Base image of Gobra to be used.'
    required: true
    default: 'ghcr.io/viperproject/gobra'
  imageVersion:
    description: 'Version of the base image to be used.'
    required: true
    default: 'latest'
  headerOnly:
    description: 'Whether Gobra should only verify files with the header "// +gobra".'
    required: false
    default: '0'
  module:
    description: 'Name of current module that should be used for resolving imports.'
    required: false
  assumeInjectivityOnInhale:
    description: 'Assume injectivity of the receiver expression when inhaling quantified permissions, instead of checking it, like in Viper versions previous to 2022.02.'
    required: false
    default: '0'
outputs:
  time:
    description: 'Total verification time in seconds'
runs:
  using: 'docker'
  image: 'Dockerfile'
